### ISSUE TITLE
Support for CircleCI Workflows

### ISSUE THREAD

**Issue by jtrim** [sshaw/build-status#6]
Upon a surface-level evaluation, it doesn't look like the status of CircleCI workflows is accurately represented, i.e. if the overall workflow fails but the final build of the workflow passes, the represented build status is passing. I'm happy to try implementing support for this if my read of things is correct.

Thanks for your work on this!

**Comment by sshaw** [comment]
Hi,

>  if the overall workflow fails but the final build of the workflow passes, the represented build status is passing

I haven't used workflows but technically is sounds like it's working correctly it's just providing the wrong information. 

Is one able to determine the overall workflow status given the current API call and status mapping?

This would definitely be a nice addition.

**Comment by jtrim** [comment]
> I haven't used workflows but technically is sounds like it's working correctly it's just providing the wrong information.

Yeah, that would be my assessment as well.

> Is one able to determine the overall workflow status given the current API call and status mapping?

Not sure right off the top of my head. I'll check it out and open a PR with the changes if it's feasible.

**Comment by jtrim** [comment]
Oddly enough, it looks like CircleCI doesn't include workflow information or API endpoints.
